name: Reusable .NET CI Pipeline

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      dotnet-version:
        required: false
        type: string
        default: '9.0.x'
      run-tests:
        required: false
        type: boolean
        default: true
      run-integration-tests:
        required: false
        type: boolean
        default: false
      run-security-scan:
        required: false
        type: boolean
        default: false
      build-configuration:
        required: false
        type: string
        default: 'Release'
      database-type:
        required: false
        type: string
        default: 'mssql'
      requires-github-packages:
        required: false
        type: boolean
        default: false

jobs:
  ci:
    uses: ./.github/workflows/dotnet-microservice-full.yml
    with:
      service-name: ${{ inputs.service-name }}
      dotnet-version: ${{ inputs.dotnet-version }}
      run-tests: ${{ inputs.run-tests }}
      run-integration-tests: ${{ inputs.run-integration-tests }}
      run-security-scan: ${{ inputs.run-security-scan }}
      build-configuration: ${{ inputs.build-configuration }}
      database-type: ${{ inputs.database-type }}
      requires-github-packages: ${{ inputs.requires-github-packages }}
      build-docker: false
      deploy-to-dev: false
      deploy-to-prod: false
    secrets: inherit
  